version: '3'
services:
  back:
    env_file:
      - common.env
    build: back
    networks:
      - main
  front:
    env_file:
      - common.env
    build: front
    networks:
      - main
  s3:
    env_file:
      - common.env
    image: scireum/s3-ninja
    networks:
      - main
  web:
    env_file:
      - common.env
    build: web
    ports:
      - 80:80
    networks:
      - main
  
  pg:
    build: pg
    env_file:
      - common.env
    networks:
      - main
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    env_file:
      - common.env
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - main

networks:
  main:

volumes:
  pgdata:
